{
 "title": "API Performance",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Panel Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(api_requests_total{status_code=~\"5..\"}[5m]))\r\n/\r\nsum(rate(api_requests_total[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Latency P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum(rate(api_request_duration_seconds_bucket[5m])) by (le)\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(api_requests_total[1m]))\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}