{
 "title": "Model Performance & Drift",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "data drift detected",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "data_drift_detected\r\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "model mape",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_mape_score\r\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "model r2_score",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_r2_score\r\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "model mae",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_mae_score\r\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "model_rmse_score",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_rmse_score\r\n", "legendFormat": "__auto" }
   ]
  }
 ]
}